// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09HIW6nEVEAWdTpZOMPKaI1mjzpk_xWE',
    appId: '1:1001100317167:web:d80d20c2406f57fce7a61a',
    messagingSenderId: '1001100317167',
    projectId: 'h2optimizer-c5757',
    authDomain: 'h2optimizer-c5757.firebaseapp.com',
    storageBucket: 'h2optimizer-c5757.firebasestorage.app',
    measurementId: 'G-SR02SPBYHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEmpq-FHWESah3Mlcc4s3d5725k45wsEg',
    appId: '1:1001100317167:android:4899fe910cf6439ce7a61a',
    messagingSenderId: '1001100317167',
    projectId: 'h2optimizer-c5757',
    storageBucket: 'h2optimizer-c5757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATwh0A0bWYJ67s3h3UTreKAOak-QrqR9k',
    appId: '1:1001100317167:ios:f1afbbd5275375cde7a61a',
    messagingSenderId: '1001100317167',
    projectId: 'h2optimizer-c5757',
    storageBucket: 'h2optimizer-c5757.firebasestorage.app',
    iosClientId: '1001100317167-9htqa9ie8qj2e4asnnmaubs8afs03s3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.h2optimizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATwh0A0bWYJ67s3h3UTreKAOak-QrqR9k',
    appId: '1:1001100317167:ios:f1afbbd5275375cde7a61a',
    messagingSenderId: '1001100317167',
    projectId: 'h2optimizer-c5757',
    storageBucket: 'h2optimizer-c5757.firebasestorage.app',
    iosClientId: '1001100317167-9htqa9ie8qj2e4asnnmaubs8afs03s3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.h2optimizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA09HIW6nEVEAWdTpZOMPKaI1mjzpk_xWE',
    appId: '1:1001100317167:web:797c4b4efce2a7e8e7a61a',
    messagingSenderId: '1001100317167',
    projectId: 'h2optimizer-c5757',
    authDomain: 'h2optimizer-c5757.firebaseapp.com',
    storageBucket: 'h2optimizer-c5757.firebasestorage.app',
    measurementId: 'G-29XYFP9GRS',
  );
}
