name: h2optimizer
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  get: ^4.6.6
  http: ^1.2.1
  provider: ^6.1.5+1
  flutter_bluetooth_classic_serial: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/
